# Generated by Django 5.1.6 on 2025-06-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='album',
            name='total_duration',
        ),
        migrations.AddField(
            model_name='album',
            name='duration',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
