# Generated by Django 5.1.6 on 2025-07-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_remove_album_cover_remove_album_total_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='duration',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='tracks',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('fav_albums', models.ManyToManyField(blank=True, to='music_app.album')),
            ],
        ),
    ]
