# Generated by Django 5.1.6 on 2025-07-08 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_userprofile_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.userprofile')),
            ],
            options={
                'unique_together': {('user', 'album')},
            },
        ),
    ]
